import type { MoodDefinition, MoodId } from "./types";

export const MOOD_DEFINITIONS: Record<MoodId, MoodDefinition> = {
  cozy: {
    id: "cozy",
    label: "Cozy & Comforting",
    emoji: "😌",
    description: "Warm, low-stakes stories to wrap yourself in.",
    accent: "#F59E0B",
    query: {
      with_genres: "10751,35,10749",
      without_genres: "27,10752,53",
      vote_average_gte: 6.5,
      vote_count_gte: 500,
      sort_by: "popularity.desc",
    },
  },
  "mind-bending": {
    id: "mind-bending",
    label: "Mind-Bending",
    emoji: "🧠",
    description: "Films that twist your perception of reality.",
    accent: "#06B6D4",
    query: {
      with_genres: "9648,878,53",
      vote_average_gte: 7.0,
      vote_count_gte: 1000,
      sort_by: "vote_average.desc",
    },
  },
  "edge-of-seat": {
    id: "edge-of-seat",
    label: "Edge of Seat",
    emoji: "😰",
    description: "Tense, gripping rides that grab and hold.",
    accent: "#EF4444",
    query: {
      with_genres: "53,80",
      vote_average_gte: 6.5,
      vote_count_gte: 500,
      with_runtime_lte: 150,
      sort_by: "popularity.desc",
    },
  },
  laugh: {
    id: "laugh",
    label: "Laugh Out Loud",
    emoji: "😂",
    description: "Pure comedy. No baggage, just laughs.",
    accent: "#FACC15",
    query: {
      with_genres: "35",
      without_genres: "18,27",
      vote_average_gte: 6.5,
      vote_count_gte: 500,
      sort_by: "popularity.desc",
    },
  },
  "good-cry": {
    id: "good-cry",
    label: "Good Cry",
    emoji: "😢",
    description: "The kind of sad that feels somehow good.",
    accent: "#EC4899",
    query: {
      with_genres: "18,10749",
      vote_average_gte: 7.0,
      vote_count_gte: 1000,
      sort_by: "vote_average.desc",
    },
  },
  escape: {
    id: "escape",
    label: "Escape Reality",
    emoji: "🌌",
    description: "Big worlds, bigger imaginations. Take me somewhere else.",
    accent: "#A855F7",
    query: {
      with_genres: "14,12,878",
      vote_average_gte: 6.5,
      vote_count_gte: 1000,
      with_runtime_gte: 100,
      sort_by: "popularity.desc",
    },
  },
  "date-night": {
    id: "date-night",
    label: "Date Night",
    emoji: "💕",
    description: "Chemistry, charm, and just enough heart.",
    accent: "#F43F5E",
    query: {
      with_genres: "10749,35",
      vote_average_gte: 6.5,
      vote_count_gte: 500,
      with_runtime_lte: 130,
      sort_by: "popularity.desc",
    },
  },
  adrenaline: {
    id: "adrenaline",
    label: "Adrenaline Rush",
    emoji: "💥",
    description: "Action that pins you to the seat.",
    accent: "#F97316",
    query: {
      with_genres: "28,12",
      vote_average_gte: 6.5,
      vote_count_gte: 1000,
      sort_by: "popularity.desc",
    },
  },
  "dark-gritty": {
    id: "dark-gritty",
    label: "Dark & Gritty",
    emoji: "🌑",
    description: "Noir, crime, and the shadows in between.",
    accent: "#991B1B",
    query: {
      with_genres: "80,18,53",
      vote_average_gte: 7.0,
      vote_count_gte: 500,
      sort_by: "vote_average.desc",
    },
  },
  curious: {
    id: "curious",
    label: "Curious Mind",
    emoji: "🔍",
    description: "Real stories, real people, real perspectives.",
    accent: "#10B981",
    query: {
      with_genres: "99,36",
      vote_average_gte: 7.0,
      vote_count_gte: 200,
      sort_by: "vote_average.desc",
    },
  },
};

export const MOOD_LIST = Object.values(MOOD_DEFINITIONS);
